//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.24 at 03:44:19 PM CEST 
//


package es.gob.afirma.ws.client.modelo;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the es.gob.afirma.ws.client.modelo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ConsultarIdentidadResResponse_QNAME = new QName("http://servicios.mdef.es/dicodef/consultarDICODEF.xsd", "ConsultarIdentidadResResponse");
    private final static QName _ObtenerCertificadoResponse_QNAME = new QName("http://servicios.mdef.es/dicodef/consultarDICODEF.xsd", "obtenerCertificadoResponse");
    private final static QName _ConsultarIdentidadSIPERDEFRequest_QNAME = new QName("http://servicios.mdef.es/dicodef/consultarDICODEF.xsd", "ConsultarIdentidadSIPERDEFRequest");
    private final static QName _ConsultarIdentidadResFault_QNAME = new QName("http://servicios.mdef.es/dicodef/consultarDICODEF.xsd", "ConsultarIdentidadResFault");
    private final static QName _ConsultarIdentidadRequest_QNAME = new QName("http://servicios.mdef.es/dicodef/consultarDICODEF.xsd", "ConsultarIdentidadRequest");
    private final static QName _ConsultarRelacionRequest_QNAME = new QName("http://servicios.mdef.es/dicodef/consultarDICODEF.xsd", "ConsultarRelacionRequest");
    private final static QName _ConsultarIdentidadTelefonoResponse_QNAME = new QName("http://servicios.mdef.es/dicodef/consultarDICODEF.xsd", "ConsultarIdentidadTelefonoResponse");
    private final static QName _ConsultarTarjetaRequest_QNAME = new QName("http://servicios.mdef.es/dicodef/consultarDICODEF.xsd", "ConsultarTarjetaRequest");
    private final static QName _ConsultarIdentidadResponse_QNAME = new QName("http://servicios.mdef.es/dicodef/consultarDICODEF.xsd", "ConsultarIdentidadResponse");
    private final static QName _ConsultarTarjetaFault_QNAME = new QName("http://servicios.mdef.es/dicodef/consultarDICODEF.xsd", "ConsultarTarjetaFault");
    private final static QName _ConsultarIdentidadExtendidaFault_QNAME = new QName("http://servicios.mdef.es/dicodef/consultarDICODEF.xsd", "ConsultarIdentidadExtendidaFault");
    private final static QName _ConsultarRelacionSituacionResponse_QNAME = new QName("http://servicios.mdef.es/dicodef/consultarDICODEF.xsd", "ConsultarRelacionSituacionResponse");
    private final static QName _ConsultarRelacionSituacionFault_QNAME = new QName("http://servicios.mdef.es/dicodef/consultarDICODEF.xsd", "ConsultarRelacionSituacionFault");
    private final static QName _ConsultarIdentidadTelefonoRequest_QNAME = new QName("http://servicios.mdef.es/dicodef/consultarDICODEF.xsd", "ConsultarIdentidadTelefonoRequest");
    private final static QName _ConsultarIdentidadSIPERDEFResponse_QNAME = new QName("http://servicios.mdef.es/dicodef/consultarDICODEF.xsd", "ConsultarIdentidadSIPERDEFResponse");
    private final static QName _ConsultarIdentidadTelefonoFault_QNAME = new QName("http://servicios.mdef.es/dicodef/consultarDICODEF.xsd", "ConsultarIdentidadTelefonoFault");
    private final static QName _ConsultarRelacionFault_QNAME = new QName("http://servicios.mdef.es/dicodef/consultarDICODEF.xsd", "ConsultarRelacionFault");
    private final static QName _ConsultarIdentidadExtendidaResponse_QNAME = new QName("http://servicios.mdef.es/dicodef/consultarDICODEF.xsd", "ConsultarIdentidadExtendidaResponse");
    private final static QName _ConsultarIdentidadResRequest_QNAME = new QName("http://servicios.mdef.es/dicodef/consultarDICODEF.xsd", "ConsultarIdentidadResRequest");
    private final static QName _ObtenerCertificadoFault_QNAME = new QName("http://servicios.mdef.es/dicodef/consultarDICODEF.xsd", "obtenerCertificadoFault");
    private final static QName _ConsultarRelacionResponse_QNAME = new QName("http://servicios.mdef.es/dicodef/consultarDICODEF.xsd", "ConsultarRelacionResponse");
    private final static QName _ConsultarIdentidadExtendidaRequest_QNAME = new QName("http://servicios.mdef.es/dicodef/consultarDICODEF.xsd", "ConsultarIdentidadExtendidaRequest");
    private final static QName _ConsultarIdentidadFault_QNAME = new QName("http://servicios.mdef.es/dicodef/consultarDICODEF.xsd", "ConsultarIdentidadFault");
    private final static QName _ObtenerCertificadoRequest_QNAME = new QName("http://servicios.mdef.es/dicodef/consultarDICODEF.xsd", "obtenerCertificadoRequest");
    private final static QName _ConsultarIdentidadSIPERDEFFault_QNAME = new QName("http://servicios.mdef.es/dicodef/consultarDICODEF.xsd", "ConsultarIdentidadSIPERDEFFault");
    private final static QName _ConsultarRelacionSituacionRequest_QNAME = new QName("http://servicios.mdef.es/dicodef/consultarDICODEF.xsd", "ConsultarRelacionSituacionRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: es.gob.afirma.ws.client.modelo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link IdentidadExtendidaType }
     * 
     */
    public IdentidadExtendidaType createIdentidadExtendidaType() {
        return new IdentidadExtendidaType();
    }

    /**
     * Create an instance of {@link IdentidadSIPERDEFType }
     * 
     */
    public IdentidadSIPERDEFType createIdentidadSIPERDEFType() {
        return new IdentidadSIPERDEFType();
    }

    /**
     * Create an instance of {@link CertificadoType }
     * 
     */
    public CertificadoType createCertificadoType() {
        return new CertificadoType();
    }

    /**
     * Create an instance of {@link ConsultarIdentidadExtendidaRequestType }
     * 
     */
    public ConsultarIdentidadExtendidaRequestType createConsultarIdentidadExtendidaRequestType() {
        return new ConsultarIdentidadExtendidaRequestType();
    }

    /**
     * Create an instance of {@link IdentidadType }
     * 
     */
    public IdentidadType createIdentidadType() {
        return new IdentidadType();
    }

    /**
     * Create an instance of {@link IdentidadResType }
     * 
     */
    public IdentidadResType createIdentidadResType() {
        return new IdentidadResType();
    }

    /**
     * Create an instance of {@link ConsultarTarjetaResponse }
     * 
     */
    public ConsultarTarjetaResponse createConsultarTarjetaResponse() {
        return new ConsultarTarjetaResponse();
    }

    /**
     * Create an instance of {@link IdentidadTelefonoType }
     * 
     */
    public IdentidadTelefonoType createIdentidadTelefonoType() {
        return new IdentidadTelefonoType();
    }

    /**
     * Create an instance of {@link UsuarioSistemaMailType }
     * 
     */
    public UsuarioSistemaMailType createUsuarioSistemaMailType() {
        return new UsuarioSistemaMailType();
    }

    /**
     * Create an instance of {@link ServiciosDicodefFaultType }
     * 
     */
    public ServiciosDicodefFaultType createServiciosDicodefFaultType() {
        return new ServiciosDicodefFaultType();
    }

    /**
     * Create an instance of {@link RelacionType }
     * 
     */
    public RelacionType createRelacionType() {
        return new RelacionType();
    }

    /**
     * Create an instance of {@link ConsultarRelacionSituacionResponseType }
     * 
     */
    public ConsultarRelacionSituacionResponseType createConsultarRelacionSituacionResponseType() {
        return new ConsultarRelacionSituacionResponseType();
    }

    /**
     * Create an instance of {@link UsuarioSistemaType }
     * 
     */
    public UsuarioSistemaType createUsuarioSistemaType() {
        return new UsuarioSistemaType();
    }

    /**
     * Create an instance of {@link CnType }
     * 
     */
    public CnType createCnType() {
        return new CnType();
    }

    /**
     * Create an instance of {@link ConsultarIdentidadExtendidaResponseType }
     * 
     */
    public ConsultarIdentidadExtendidaResponseType createConsultarIdentidadExtendidaResponseType() {
        return new ConsultarIdentidadExtendidaResponseType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentidadResType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://servicios.mdef.es/dicodef/consultarDICODEF.xsd", name = "ConsultarIdentidadResResponse")
    public JAXBElement<IdentidadResType> createConsultarIdentidadResResponse(IdentidadResType value) {
        return new JAXBElement<IdentidadResType>(_ConsultarIdentidadResResponse_QNAME, IdentidadResType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CertificadoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://servicios.mdef.es/dicodef/consultarDICODEF.xsd", name = "obtenerCertificadoResponse")
    public JAXBElement<CertificadoType> createObtenerCertificadoResponse(CertificadoType value) {
        return new JAXBElement<CertificadoType>(_ObtenerCertificadoResponse_QNAME, CertificadoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UsuarioSistemaType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://servicios.mdef.es/dicodef/consultarDICODEF.xsd", name = "ConsultarIdentidadSIPERDEFRequest")
    public JAXBElement<UsuarioSistemaType> createConsultarIdentidadSIPERDEFRequest(UsuarioSistemaType value) {
        return new JAXBElement<UsuarioSistemaType>(_ConsultarIdentidadSIPERDEFRequest_QNAME, UsuarioSistemaType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiciosDicodefFaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://servicios.mdef.es/dicodef/consultarDICODEF.xsd", name = "ConsultarIdentidadResFault")
    public JAXBElement<ServiciosDicodefFaultType> createConsultarIdentidadResFault(ServiciosDicodefFaultType value) {
        return new JAXBElement<ServiciosDicodefFaultType>(_ConsultarIdentidadResFault_QNAME, ServiciosDicodefFaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UsuarioSistemaMailType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://servicios.mdef.es/dicodef/consultarDICODEF.xsd", name = "ConsultarIdentidadRequest")
    public JAXBElement<UsuarioSistemaMailType> createConsultarIdentidadRequest(UsuarioSistemaMailType value) {
        return new JAXBElement<UsuarioSistemaMailType>(_ConsultarIdentidadRequest_QNAME, UsuarioSistemaMailType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UsuarioSistemaType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://servicios.mdef.es/dicodef/consultarDICODEF.xsd", name = "ConsultarRelacionRequest")
    public JAXBElement<UsuarioSistemaType> createConsultarRelacionRequest(UsuarioSistemaType value) {
        return new JAXBElement<UsuarioSistemaType>(_ConsultarRelacionRequest_QNAME, UsuarioSistemaType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentidadTelefonoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://servicios.mdef.es/dicodef/consultarDICODEF.xsd", name = "ConsultarIdentidadTelefonoResponse")
    public JAXBElement<IdentidadTelefonoType> createConsultarIdentidadTelefonoResponse(IdentidadTelefonoType value) {
        return new JAXBElement<IdentidadTelefonoType>(_ConsultarIdentidadTelefonoResponse_QNAME, IdentidadTelefonoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UsuarioSistemaType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://servicios.mdef.es/dicodef/consultarDICODEF.xsd", name = "ConsultarTarjetaRequest")
    public JAXBElement<UsuarioSistemaType> createConsultarTarjetaRequest(UsuarioSistemaType value) {
        return new JAXBElement<UsuarioSistemaType>(_ConsultarTarjetaRequest_QNAME, UsuarioSistemaType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentidadType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://servicios.mdef.es/dicodef/consultarDICODEF.xsd", name = "ConsultarIdentidadResponse")
    public JAXBElement<IdentidadType> createConsultarIdentidadResponse(IdentidadType value) {
        return new JAXBElement<IdentidadType>(_ConsultarIdentidadResponse_QNAME, IdentidadType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiciosDicodefFaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://servicios.mdef.es/dicodef/consultarDICODEF.xsd", name = "ConsultarTarjetaFault")
    public JAXBElement<ServiciosDicodefFaultType> createConsultarTarjetaFault(ServiciosDicodefFaultType value) {
        return new JAXBElement<ServiciosDicodefFaultType>(_ConsultarTarjetaFault_QNAME, ServiciosDicodefFaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiciosDicodefFaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://servicios.mdef.es/dicodef/consultarDICODEF.xsd", name = "ConsultarIdentidadExtendidaFault")
    public JAXBElement<ServiciosDicodefFaultType> createConsultarIdentidadExtendidaFault(ServiciosDicodefFaultType value) {
        return new JAXBElement<ServiciosDicodefFaultType>(_ConsultarIdentidadExtendidaFault_QNAME, ServiciosDicodefFaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConsultarRelacionSituacionResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://servicios.mdef.es/dicodef/consultarDICODEF.xsd", name = "ConsultarRelacionSituacionResponse")
    public JAXBElement<ConsultarRelacionSituacionResponseType> createConsultarRelacionSituacionResponse(ConsultarRelacionSituacionResponseType value) {
        return new JAXBElement<ConsultarRelacionSituacionResponseType>(_ConsultarRelacionSituacionResponse_QNAME, ConsultarRelacionSituacionResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiciosDicodefFaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://servicios.mdef.es/dicodef/consultarDICODEF.xsd", name = "ConsultarRelacionSituacionFault")
    public JAXBElement<ServiciosDicodefFaultType> createConsultarRelacionSituacionFault(ServiciosDicodefFaultType value) {
        return new JAXBElement<ServiciosDicodefFaultType>(_ConsultarRelacionSituacionFault_QNAME, ServiciosDicodefFaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UsuarioSistemaMailType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://servicios.mdef.es/dicodef/consultarDICODEF.xsd", name = "ConsultarIdentidadTelefonoRequest")
    public JAXBElement<UsuarioSistemaMailType> createConsultarIdentidadTelefonoRequest(UsuarioSistemaMailType value) {
        return new JAXBElement<UsuarioSistemaMailType>(_ConsultarIdentidadTelefonoRequest_QNAME, UsuarioSistemaMailType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentidadSIPERDEFType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://servicios.mdef.es/dicodef/consultarDICODEF.xsd", name = "ConsultarIdentidadSIPERDEFResponse")
    public JAXBElement<IdentidadSIPERDEFType> createConsultarIdentidadSIPERDEFResponse(IdentidadSIPERDEFType value) {
        return new JAXBElement<IdentidadSIPERDEFType>(_ConsultarIdentidadSIPERDEFResponse_QNAME, IdentidadSIPERDEFType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiciosDicodefFaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://servicios.mdef.es/dicodef/consultarDICODEF.xsd", name = "ConsultarIdentidadTelefonoFault")
    public JAXBElement<ServiciosDicodefFaultType> createConsultarIdentidadTelefonoFault(ServiciosDicodefFaultType value) {
        return new JAXBElement<ServiciosDicodefFaultType>(_ConsultarIdentidadTelefonoFault_QNAME, ServiciosDicodefFaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiciosDicodefFaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://servicios.mdef.es/dicodef/consultarDICODEF.xsd", name = "ConsultarRelacionFault")
    public JAXBElement<ServiciosDicodefFaultType> createConsultarRelacionFault(ServiciosDicodefFaultType value) {
        return new JAXBElement<ServiciosDicodefFaultType>(_ConsultarRelacionFault_QNAME, ServiciosDicodefFaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentidadExtendidaType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://servicios.mdef.es/dicodef/consultarDICODEF.xsd", name = "ConsultarIdentidadExtendidaResponse")
    public JAXBElement<IdentidadExtendidaType> createConsultarIdentidadExtendidaResponse(IdentidadExtendidaType value) {
        return new JAXBElement<IdentidadExtendidaType>(_ConsultarIdentidadExtendidaResponse_QNAME, IdentidadExtendidaType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UsuarioSistemaType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://servicios.mdef.es/dicodef/consultarDICODEF.xsd", name = "ConsultarIdentidadResRequest")
    public JAXBElement<UsuarioSistemaType> createConsultarIdentidadResRequest(UsuarioSistemaType value) {
        return new JAXBElement<UsuarioSistemaType>(_ConsultarIdentidadResRequest_QNAME, UsuarioSistemaType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiciosDicodefFaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://servicios.mdef.es/dicodef/consultarDICODEF.xsd", name = "obtenerCertificadoFault")
    public JAXBElement<ServiciosDicodefFaultType> createObtenerCertificadoFault(ServiciosDicodefFaultType value) {
        return new JAXBElement<ServiciosDicodefFaultType>(_ObtenerCertificadoFault_QNAME, ServiciosDicodefFaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RelacionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://servicios.mdef.es/dicodef/consultarDICODEF.xsd", name = "ConsultarRelacionResponse")
    public JAXBElement<RelacionType> createConsultarRelacionResponse(RelacionType value) {
        return new JAXBElement<RelacionType>(_ConsultarRelacionResponse_QNAME, RelacionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UsuarioSistemaType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://servicios.mdef.es/dicodef/consultarDICODEF.xsd", name = "ConsultarIdentidadExtendidaRequest")
    public JAXBElement<UsuarioSistemaType> createConsultarIdentidadExtendidaRequest(UsuarioSistemaType value) {
        return new JAXBElement<UsuarioSistemaType>(_ConsultarIdentidadExtendidaRequest_QNAME, UsuarioSistemaType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiciosDicodefFaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://servicios.mdef.es/dicodef/consultarDICODEF.xsd", name = "ConsultarIdentidadFault")
    public JAXBElement<ServiciosDicodefFaultType> createConsultarIdentidadFault(ServiciosDicodefFaultType value) {
        return new JAXBElement<ServiciosDicodefFaultType>(_ConsultarIdentidadFault_QNAME, ServiciosDicodefFaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UsuarioSistemaType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://servicios.mdef.es/dicodef/consultarDICODEF.xsd", name = "obtenerCertificadoRequest")
    public JAXBElement<UsuarioSistemaType> createObtenerCertificadoRequest(UsuarioSistemaType value) {
        return new JAXBElement<UsuarioSistemaType>(_ObtenerCertificadoRequest_QNAME, UsuarioSistemaType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiciosDicodefFaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://servicios.mdef.es/dicodef/consultarDICODEF.xsd", name = "ConsultarIdentidadSIPERDEFFault")
    public JAXBElement<ServiciosDicodefFaultType> createConsultarIdentidadSIPERDEFFault(ServiciosDicodefFaultType value) {
        return new JAXBElement<ServiciosDicodefFaultType>(_ConsultarIdentidadSIPERDEFFault_QNAME, ServiciosDicodefFaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UsuarioSistemaType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://servicios.mdef.es/dicodef/consultarDICODEF.xsd", name = "ConsultarRelacionSituacionRequest")
    public JAXBElement<UsuarioSistemaType> createConsultarRelacionSituacionRequest(UsuarioSistemaType value) {
        return new JAXBElement<UsuarioSistemaType>(_ConsultarRelacionSituacionRequest_QNAME, UsuarioSistemaType.class, null, value);
    }

}
