//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.23 at 09:19:58 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://servicios.mdef.es/dicodef/consultarDICODEF.xsd")
package es.gob.afirma.ws.client.modelo;
